### PR TITLE
Lps 75783

### PR DESCRIPTION
**Pull request by lanceji92674957**
Hi Shuyang,

This pull is to fix localization of dynamic-data-mapping-form-web, which came after the last fix for all dynamic data mapping modules.
After this pull got merged, the configuration localization test should be ready to be opened.

Thanks.
Lance

### CODE REVIEW

**Comment by lanceji92674957** [comment]
ci:test

**Comment by shuyangzhou** [comment]
See https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/691

**Comment by shuyangzhou** [comment]
@lanceji92674957 please watch out on the pull, once it is merged, send me the pull to turn on the test. Thanks!

**Comment by lanceji92674957** [comment]
ok

**Pull request closed without merging**
